title: status | tensevntysevn
buildFuture: true
languageCode: en
defaultContentLanguage: en
baseURL: https://status.tensevntysevn.cf/
enableGitInfo: true

params:
  categories:
    - name: Web Services
    - name: API Services
    - name: Core Services
      description: Important, backend services that support tensevntysevn's online services.
      closed: true

  systems:
    - name: Website & Blog
      description: The official tensevntysevn website and blog.
      category: Web Services
    - name: The Fresh Website
      description: The official website for the Fresh Project. Includes the main site, and associated web apps.
      category: Web Services
    - name: Witzy
      description: The easy and witty game for all ages!
      category: Web Services

    - name: Over-the-Air (OTA) Updates
      description: This service handles over-the-air updates for all ROMs and apps released by tensevntysevn.
      category: API Services
    - name: Fresh Addon Store
      description: The official Fresh Addons store. Separate listing due to separate maintenance periods from OTA API.
      category: API Services
    - name: Clembot for Discord
      description: The bot used for the Fresh Community Discord server.
      category: API Services

    - name: CloudFlare
      description: The primary DNS and edge network host of all tensevntysevn services.
      category: Core Services
    - name: Netlify
      description: Secondary mirror of select services.
      category: Core Services
    - name: Vercel
      description: Tertiary mirror of select services, as well as the host for Witzy.
      category: Core Services
    - name: SourceForge
      description: Provides downloads for large files distributed under tensevntysevn.
      category: Core Services
    - name: Yandex.Mail
      description: The mail service for @tensevntysevn.cf emails.
      category: Core Services

  dateFormat: January 2, 2006 | 3:04 PM UTC
  shortDateFormat: 3:04 PM UTC | Jan 2
  useRelativeTime: true
  skipSeconds: true
  enableLastMod: true
  useLargeHeaderDesign: false
  incidentHistoryFormat: "yearly"
  disableIncidentHistory: false
  disableDarkMode: false
  useLogo: true
  logo: logo.png
  description: All services are closely monitored, with interruptions as well as announcements being posted here. Make sure to check back from time-to-time.
  disableComplexCalculations: false
  incidentPostsPerPage: 10
  brand: "#131A26"
  ok: "#008000"
  disrupted: "#cc4400"
  down: "#e60000"
  notice: "#24478f"
  alwaysKeepBrandColor: true
  headerTextColor: white
  googleAnalytics: UA-00000000-1

# These options affect the core of cState.
# Please do not change them if you do not
# know what you are doing.
preserveTaxonomyNames: true

taxonomies:
  affected: affected

outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss

outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
